### ISSUE TITLE
The regex output is incorrect

### ISSUE THREAD

**Issue by cdeutsch** [obahareth/are-you-es5#10]
It should be round brackets, not square brackets.

Example:
`/node_modules\/(?!(pretty\-bytes|query\-string|strict\-uri\-encode))/`

Square brackets means a character set.

The reason square brackets appears to work is that most `node_modules` will get compiled even if they don't need to be.

**Comment by obahareth** [comment]
Oh you're quite right @cdeutsch, I'll get a fix out for that soon.

**Comment by obahareth** [comment]
Fixed and released as version 1.1.1 @cdeutsch!

**Comment by cdeutsch** [comment]
That was fast! Thanks!
