### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by endoval** [obahareth/are-you-es5#18]
#Hi Omar,

first of all: Thanks for the great module, it really helps. Sadly, there seems to be something off when having are-you-es5 as a dev dependency and running npm install multiple times to pull in updates:

`⇒  npm install
npm ERR! path /example/node_modules/are-you-es5
npm ERR! code EISGIT
npm ERR! git /example/node_modules/are-you-es5: Appears to be a git repo or submodule.
npm ERR! git     /example/node_modules/are-you-es5
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.`

Seems like you have to remove the .git folder from the published package in order to fix that behaviour.

Thanks in advance,

Fabian

PS: Similar issue on another project as a reference https://github.com/react-native-community/react-native-safe-area-view/issues/69

**Comment by obahareth** [comment]
@endoval I am so sorry for your experience, I thought I already ignored it. I updated the `.npmignore` to slim down the package more and remove the .git folder as well and published version 1.3.2 to npm. I hope this solves your issue!

**Comment by endoval** [comment]
@obahareth Thank you for the quick fix. Worked for me! :)
