### ISSUE TITLE
Version 2.0.1 contains "\r" in build

### ISSUE THREAD

**Issue by madsmadsen** [obahareth/are-you-es5#44]
Release version 2.0.1 has a "\r" in `./dist/cli.js` on line 1, so it cannot be executed on non-windows systems.

```bash
env: node\r: No such file or directory
```

**Comment by obahareth** [comment]
@madsmadsen Thanks for reporting this. I published 2.0.2 with a fix for this and added `lf` line endings to both our tsconfig.json (89c321148e15bf41bd0e9188301102b20d373494) and added a .editorconfig (853f95f670f0cedb9824cd9bbbaa857b740a14a6).
