### ISSUE TITLE
Should the script ignore adding babel/webpack plugins to the exclude regex by itself?

### ISSUE THREAD

**Issue by obahareth** [obahareth/are-you-es5#6]
Most people would have webpack/babel-specific stuff only in `devDependencies`, but for folks who build on something like Heroku rather than on CI they'll probably have them in `dependencies`, should we exclude them from the regex output ourselves? Or should we add an option to do that.

**Comment by cdeutsch** [comment]
I find myself in this situation.

An option would be great.

Might have to be even more generic than just babel/webpack (although a flag for those individually would be nice too)

`are-you-es5` creates this list for me
```
/node_modules/(?!(@babel/core|@babel/plugin-proposal-class-properties|@babel/plugin-proposal-decorators|@babel/plugin-proposal-do-expressions|@babel/plugin-proposal-export-default-from|@babel/plugin-proposal-export-namespace-from|@babel/plugin-proposal-function-bind|@babel/plugin-proposal-function-sent|@babel/plugin-proposal-json-strings|@babel/plugin-proposal-logical-assignment-operators|@babel/plugin-proposal-nullish-coalescing-operator|@babel/plugin-proposal-numeric-separator|@babel/plugin-proposal-optional-chaining|@babel/plugin-proposal-pipeline-operator|@babel/plugin-proposal-throw-expressions|@babel/plugin-syntax-dynamic-import|@babel/plugin-syntax-import-meta|@babel/preset-env|@babel/preset-react|babel-jest|babel-loader|case-sensitive-paths-webpack-plugin|chalk|copy-webpack-plugin|cross-spawn|cspell|css-loader|eslint|eslint-plugin-import|eslint-plugin-react|file-loader|fork-ts-checker-notifier-webpack-plugin|fork-ts-checker-webpack-plugin|fs-extra|html-webpack-plugin|jest|jest-cli|jest-image-snapshot|json-loader|lint-staged|postcss-loader|prettier|pretty-bytes|query-string|terser-webpack-plugin|tslint-config-prettier|tslint-microsoft-contrib|tslint-react|url-loader|webpack|webpack-build-notifier|webpack-bundle-analyzer|webpack-cli|webpack-dev-server))/
```

Of which, I shrink down to:
```
/node_modules\/(?!(pretty-bytes|query-string))/
```

**Comment by obahareth** [comment]
I think we could perhaps create an "ignore regex" with a flag to optionally disregard that, or perhaps an option to provide your own ignore regex. We could have a default regex in the repo for `babel-plugin-.*` and `@babel/.*`, and so on. I'm not sure how to handle webpack plugins though, I don't think all of them follow a naming convention and may have to be added manually.

**Comment by cdeutsch** [comment]
Yeah webpack is harder. Some follow the `*-loader` or `*-plugin` convention, but that's pretty generic.

A way to provide your own regex would work 👍

**Comment by obahareth** [comment]
@cdeutsch Version 1.3.0 ignores babel/webpack packages by default and provides an option to turn that off if undesirable. Closing this issue.
